language: go
sudo: false
branches:
  only: [master]
go: "1.14"

# executes all but fails if any failed
# keep in sync with .travis.yml
script:
- go build .
- go get github.com/grosser/go-testcov
- go-testcov . -covermode atomic
- ruby test.rb -v
- go mod tidy && git diff --exit-code
- go fmt . && git diff --exit-code

