language: go
sudo: false
branches:
  only: [master]
go: "1.14"
script: # executes all but fails if any failed
- go build .
- go get github.com/grosser/go-testcov
- go-testcov . -covermode atomic
- go mod tidy && git diff --exit-code
- go fmt . && git diff --exit-code

